# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './Design_ui/login_wind.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(411, 367)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(90, 10, 231, 41))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(20, 50, 371, 51))
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(20, 130, 71, 31))
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(20, 180, 71, 31))
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName("label_4")
        self.login_line = QtWidgets.QLineEdit(Form)
        self.login_line.setGeometry(QtCore.QRect(100, 130, 291, 31))
        self.login_line.setObjectName("login_line")
        self.passw_line = QtWidgets.QLineEdit(Form)
        self.passw_line.setGeometry(QtCore.QRect(100, 180, 291, 31))
        self.passw_line.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passw_line.setObjectName("passw_line")
        self.log_in_pushButton = QtWidgets.QPushButton(Form)
        self.log_in_pushButton.setGeometry(QtCore.QRect(20, 240, 371, 41))
        self.log_in_pushButton.setObjectName("log_in_pushButton")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(20, 310, 351, 41))
        self.label_5.setWordWrap(True)
        self.label_5.setObjectName("label_5")
        self.registr_pushButton = QtWidgets.QPushButton(Form)
        self.registr_pushButton.setGeometry(QtCore.QRect(250, 310, 141, 41))
        self.registr_pushButton.setObjectName("registr_pushButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Авторизация"))
        self.label.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600; font-style:italic;\">Добро пожаловать!</span></p></body></html>"))
        self.label_2.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt;\">Необходимо пройти процесс авторизации прежде чем приступить к работе с методами обработки данных в больших компьютерных диапазонах.</span></p></body></html>"))
        self.label_3.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt;\">Логин:</span></p></body></html>"))
        self.label_4.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt;\">Пароль:</span></p></body></html>"))
        self.log_in_pushButton.setText(_translate("Form", "Вход"))
        self.label_5.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt;\">Если Вы еще не зарегистрированы -&gt;</span></p></body></html>"))
        self.registr_pushButton.setText(_translate("Form", "Регистрация"))
