# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './Design_ui/new_val_wind.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(490, 359)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(110, 10, 251, 31))
        self.label.setObjectName("label")
        self.label_new_name = QtWidgets.QLabel(Form)
        self.label_new_name.setGeometry(QtCore.QRect(20, 50, 451, 31))
        self.label_new_name.setObjectName("label_new_name")
        self.new_name_line = QtWidgets.QLineEdit(Form)
        self.new_name_line.setGeometry(QtCore.QRect(20, 80, 451, 31))
        self.new_name_line.setObjectName("new_name_line")
        self.label_type = QtWidgets.QLabel(Form)
        self.label_type.setGeometry(QtCore.QRect(20, 130, 451, 31))
        self.label_type.setObjectName("label_type")
        self.comboBox = QtWidgets.QComboBox(Form)
        self.comboBox.setGeometry(QtCore.QRect(20, 160, 451, 31))
        self.comboBox.setObjectName("comboBox")
        self.label_new_type_or_file = QtWidgets.QLabel(Form)
        self.label_new_type_or_file.setGeometry(QtCore.QRect(20, 190, 451, 31))
        self.label_new_type_or_file.setObjectName("label_new_type_or_file")
        self.new_type_or_file_line = QtWidgets.QLineEdit(Form)
        self.new_type_or_file_line.setGeometry(QtCore.QRect(20, 220, 451, 31))
        self.new_type_or_file_line.setObjectName("new_type_or_file_line")
        self.choose_file_pushButton = QtWidgets.QPushButton(Form)
        self.choose_file_pushButton.setGeometry(QtCore.QRect(360, 260, 111, 41))
        self.choose_file_pushButton.setObjectName("choose_file_pushButton")
        self.save_new_val_pushButton = QtWidgets.QPushButton(Form)
        self.save_new_val_pushButton.setGeometry(QtCore.QRect(360, 310, 111, 41))
        self.save_new_val_pushButton.setObjectName("save_new_val_pushButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Новое значение"))
        self.label.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Добавление нового значения</span></p></body></html>"))
        self.label_new_name.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt;\">Ф</span></p></body></html>"))
        self.label_type.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt;\">Ф</span></p></body></html>"))
        self.label_new_type_or_file.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt;\">Или введите новое:</span></p></body></html>"))
        self.choose_file_pushButton.setText(_translate("Form", "Выбрать файл"))
        self.save_new_val_pushButton.setText(_translate("Form", "Сохранить"))
