# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './Design_ui/reg_wind.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(581, 404)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(170, 10, 231, 41))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(20, 30, 461, 51))
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(90, 90, 71, 31))
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(130, 130, 51, 31))
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(90, 170, 81, 31))
        self.label_5.setWordWrap(True)
        self.label_5.setObjectName("label_5")
        self.label_login = QtWidgets.QLabel(Form)
        self.label_login.setGeometry(QtCore.QRect(110, 210, 71, 31))
        self.label_login.setWordWrap(True)
        self.label_login.setObjectName("label_login")
        self.label_pass_or_mail = QtWidgets.QLabel(Form)
        self.label_pass_or_mail.setGeometry(QtCore.QRect(100, 250, 71, 31))
        self.label_pass_or_mail.setWordWrap(True)
        self.label_pass_or_mail.setObjectName("label_pass_or_mail")
        self.label_pass2_or_lev = QtWidgets.QLabel(Form)
        self.label_pass2_or_lev.setGeometry(QtCore.QRect(20, 280, 151, 41))
        self.label_pass2_or_lev.setWordWrap(True)
        self.label_pass2_or_lev.setObjectName("label_pass2_or_lev")
        self.reg_pushButton = QtWidgets.QPushButton(Form)
        self.reg_pushButton.setGeometry(QtCore.QRect(20, 340, 541, 41))
        self.reg_pushButton.setObjectName("reg_pushButton")
        self.passw2_line_reg = QtWidgets.QLineEdit(Form)
        self.passw2_line_reg.setGeometry(QtCore.QRect(180, 290, 381, 31))
        self.passw2_line_reg.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passw2_line_reg.setObjectName("passw2_line_reg")
        self.passw_or_mail_line_reg = QtWidgets.QLineEdit(Form)
        self.passw_or_mail_line_reg.setGeometry(QtCore.QRect(180, 250, 381, 31))
        self.passw_or_mail_line_reg.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passw_or_mail_line_reg.setObjectName("passw_or_mail_line_reg")
        self.login_line_reg = QtWidgets.QLineEdit(Form)
        self.login_line_reg.setGeometry(QtCore.QRect(180, 210, 381, 31))
        self.login_line_reg.setObjectName("login_line_reg")
        self.patron_line = QtWidgets.QLineEdit(Form)
        self.patron_line.setGeometry(QtCore.QRect(180, 170, 381, 31))
        self.patron_line.setObjectName("patron_line")
        self.firstname_line = QtWidgets.QLineEdit(Form)
        self.firstname_line.setGeometry(QtCore.QRect(180, 130, 381, 31))
        self.firstname_line.setObjectName("firstname_line")
        self.lastname_line = QtWidgets.QLineEdit(Form)
        self.lastname_line.setGeometry(QtCore.QRect(180, 90, 381, 31))
        self.lastname_line.setObjectName("lastname_line")
        self.lev_acc_comboBox = QtWidgets.QComboBox(Form)
        self.lev_acc_comboBox.setGeometry(QtCore.QRect(180, 290, 381, 31))
        self.lev_acc_comboBox.setObjectName("lev_acc_comboBox")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Регистрация"))
        self.label.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600; font-style:italic;\">Регистрация</span></p></body></html>"))
        self.label_2.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt;\">Пожалуйста, заполните все поля для прохождения регистрации.</span></p></body></html>"))
        self.label_3.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt;\">Фамилия:</span></p></body></html>"))
        self.label_4.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt;\">Имя:</span></p></body></html>"))
        self.label_5.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt;\">Отчество:</span></p></body></html>"))
        self.label_login.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt;\">Логин:</span></p></body></html>"))
        self.label_pass_or_mail.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt;\">Пароль:</span></p></body></html>"))
        self.label_pass2_or_lev.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt;\">Повторите пароль:</span></p></body></html>"))
        self.reg_pushButton.setText(_translate("Form", "Регистрация"))
